// This file implements functions for interacting with the Local APIC (Advanced
// Programmable Interrupt Controller). Each CPU in a multiprocessor system has
// its own LAPIC.
//
// Role of the Local APIC (LAPIC):
// - Receiving and Managing Interrupts: The LAPIC is responsible for receiving
//   interrupts that are local to its CPU. This includes:
//   - Timer Interrupts: Generated by the LAPIC's own programmable timer, used
//     for preemptive multitasking (scheduling).
//   - Inter-Processor Interrupts (IPIs): Sent by one CPU to another for tasks
//     like starting up other CPUs, TLB shootdowns (not fully implemented in xv6),
//     or signaling.
//   - Spurious Interrupts: Unexpected interrupts, which the LAPIC can be configured
//     to handle gracefully.
//   - Error Interrupts: Generated by the LAPIC itself if it detects an internal error.
// - Interrupt Prioritization: The LAPIC can prioritize interrupts. The Task Priority
//   Register (TPR) can be used to mask lower-priority interrupts.
// - Interrupt Distribution (in conjunction with I/O APIC): For external hardware
//   interrupts routed by the I/O APIC, the LAPIC is the final destination on the
//   target CPU.
// - End-Of-Interrupt (EOI): Interrupt handlers must signal EOI to the LAPIC
//   to indicate that an interrupt has been processed, allowing the LAPIC to
//   deliver new interrupts.
//
// Key Registers (accessed via memory-mapped I/O, `lapic` volatile pointer):
// - ID: LAPIC ID Register (identifies the LAPIC/CPU).
// - VER: Version Register.
// - TPR: Task Priority Register.
// - EOI: End Of Interrupt Register.
// - SVR: Spurious Interrupt Vector Register.
// - ESR: Error Status Register.
// - ICRLO/ICRHI: Interrupt Command Register (for sending IPIs).
// - TIMER, LINT0, LINT1, ERROR: Local Vector Table (LVT) entries for configuring
//   timer, local pins, and error interrupts.
// - TICR, TCCR, TDCR: Timer Initial Count, Current Count, and Divide Configuration registers.
//
// See Chapter 10 (Advanced Programmable Interrupt Controller (APIC)) in the
// Intel System Programming Guide, Volume 3A, for detailed information.

#include "param.h"
#include "types.h"
#include "defs.h"
#include "date.h"
#include "memlayout.h"
#include "traps.h"
#include "mmu.h"
#include "x86.h"

// Local APIC registers, divided by 4 for use as uint[] indices.
#define ID      (0x0020/4)   // ID
#define VER     (0x0030/4)   // Version
#define TPR     (0x0080/4)   // Task Priority
#define EOI     (0x00B0/4)   // EOI
#define SVR     (0x00F0/4)   // Spurious Interrupt Vector
  #define ENABLE     0x00000100   // Unit Enable
#define ESR     (0x0280/4)   // Error Status
#define ICRLO   (0x0300/4)   // Interrupt Command
  #define INIT       0x00000500   // INIT/RESET
  #define STARTUP    0x00000600   // Startup IPI
  #define DELIVS     0x00001000   // Delivery status
  #define ASSERT     0x00004000   // Assert interrupt (vs deassert)
  #define DEASSERT   0x00000000
  #define LEVEL      0x00008000   // Level triggered
  #define BCAST      0x00080000   // Send to all APICs, including self.
  #define BUSY       0x00001000
  #define FIXED      0x00000000
#define ICRHI   (0x0310/4)   // Interrupt Command [63:32]
#define TIMER   (0x0320/4)   // Local Vector Table 0 (TIMER)
  #define X1         0x0000000B   // divide counts by 1
  #define PERIODIC   0x00020000   // Periodic
#define PCINT   (0x0340/4)   // Performance Counter LVT
#define LINT0   (0x0350/4)   // Local Vector Table 1 (LINT0)
#define LINT1   (0x0360/4)   // Local Vector Table 2 (LINT1)
#define ERROR   (0x0370/4)   // Local Vector Table 3 (ERROR)
  #define MASKED     0x00010000   // Interrupt masked
#define TICR    (0x0380/4)   // Timer Initial Count
#define TCCR    (0x0390/4)   // Timer Current Count
#define TDCR    (0x03E0/4)   // Timer Divide Configuration

// `lapic` is a volatile pointer to the base address of the Local APIC's
// memory-mapped registers. It's initialized in `mp.c` after determining
// the LAPIC's physical address from ACPI/MP tables.
volatile uint *lapic;  // Initialized in mp.c

//PAGEBREAK!
// Helper function to write a value to a LAPIC register.
// `index` is the register offset (divided by 4 for uint array indexing).
// A read from `lapic[ID]` is performed after the write to ensure the write
// completes before any subsequent operations (posted writes).
static void
lapicw(int index, int value)
{
  lapic[index] = value;
  lapic[ID];  // Wait for write to finish by reading from a LAPIC register.
}

// Initialize the Local APIC for the current CPU.
// This function is called once per CPU during its startup.
// If `lapic` is null (e.g., on a uniprocessor system without an APIC, or if
// memory mapping failed), this function does nothing.
//
// Configuration steps:
// 1. Enable LAPIC Unit: Sets the Spurious Interrupt Vector Register (SVR)
//    to enable the APIC unit software-wise and specifies the vector for
//    spurious interrupts (T_IRQ0 + IRQ_SPURIOUS).
// 2. Configure Timer:
//    - Sets the timer divide configuration (TDCR) to X1 (divide by 1, effectively using bus clock).
//    - Configures the LVT Timer entry (TIMER) to be periodic and to generate
//      interrupt T_IRQ0 + IRQ_TIMER.
//    - Sets the initial count (TICR) for the timer. The timer counts down from
//      this value. When it reaches zero, an interrupt is generated, and it reloads.
//      (The value 10000000 is arbitrary and defines the timer interrupt frequency).
// 3. Mask Local Interrupt Pins: Disables LINT0 and LINT1 (local interrupt pins
//    on the processor, often connected to NMI or used for 8259A PIC compatibility)
//    by setting the MASKED bit in their LVT entries.
// 4. Mask Performance Counter Interrupt: If supported (LAPIC version >= 4),
//    disables performance counter overflow interrupts.
// 5. Map Error Interrupt: Configures the LVT Error entry to generate interrupt
//    T_IRQ0 + IRQ_ERROR if an APIC error occurs.
// 6. Clear Error Status: Clears the Error Status Register (ESR) by writing to it twice.
// 7. Acknowledge Pending Interrupts: Writes 0 to EOI register to clear any
//    pre-existing interrupt states within the LAPIC.
// 8. Synchronize Arbitration IDs: Sends a broadcast INIT Level De-Assert IPI.
//    This helps synchronize arbitration IDs in systems with multiple LAPICs.
// 9. Enable Interrupt Reception: Sets the Task Priority Register (TPR) to 0,
//    allowing the LAPIC to deliver any interrupts (i.e., no priority masking).
//    This does *not* enable interrupts globally on the CPU (that's done by `sti`).
void
lapicinit(void)
{
  if(!lapic) // Do nothing if LAPIC is not mapped.
    return;

  // Enable local APIC; set spurious interrupt vector.
  // The spurious vector is delivered if an interrupt arrives with no source or for other error conditions.
  lapicw(SVR, ENABLE | (T_IRQ0 + IRQ_SPURIOUS));

  // Configure the LAPIC timer:
  // The timer repeatedly counts down at bus frequency from lapic[TICR] and then issues an interrupt.
  // If xv6 cared more about precise timekeeping, TICR would be calibrated using an external time source.
  lapicw(TDCR, X1); // Set timer divide configuration (divide by 1).
  lapicw(TIMER, PERIODIC | (T_IRQ0 + IRQ_TIMER)); // Set timer to periodic mode, vector T_IRQ0 + IRQ_TIMER.
  lapicw(TICR, 10000000); // Set initial count for the timer (determines interrupt frequency).

  // Disable local interrupt lines (LINT0, LINT1) by masking them.
  // These are often connected to an 8259A PIC in legacy systems or can be NMI.
  lapicw(LINT0, MASKED);
  lapicw(LINT1, MASKED);

  // Disable performance counter overflow interrupts if the LAPIC supports them (version >= 4).
  if(((lapic[VER]>>16) & 0xFF) >= 4)
    lapicw(PCINT, MASKED);

  // Map the APIC error interrupt to vector T_IRQ0 + IRQ_ERROR.
  lapicw(ERROR, T_IRQ0 + IRQ_ERROR);

  // Clear the error status register (ESR). Requires two writes: first write allows
  // the register to be updated, second write clears it.
  lapicw(ESR, 0);
  lapicw(ESR, 0);

  // Acknowledge any outstanding interrupts that might have been pending in the LAPIC
  // before initialization. This clears the In-Service Register (ISR) for the highest
  // priority pending interrupt.
  lapicw(EOI, 0);

  // Send an Init Level De-Assert IPI to all APICs (including self) to synchronize arbitration IDs.
  // This is part of the MP initialization sequence.
  lapicw(ICRHI, 0); // Destination field is 0 for BCAST if physical destination mode.
  lapicw(ICRLO, BCAST | INIT | LEVEL); // Broadcast, INIT message, Level triggered.
  while(lapic[ICRLO] & DELIVS) // Wait for delivery status to clear (IPI sent).
    ;

  // Enable interrupts on the APIC by setting Task Priority Register (TPR) to 0.
  // A TPR of 0 means the APIC will attempt to deliver any interrupt regardless of its priority.
  // This does NOT enable interrupts on the processor itself (that's `sti`).
  lapicw(TPR, 0);
}

// Get the current CPU's Local APIC ID.
// The ID is stored in the upper 8 bits of the LAPIC ID Register.
// Returns 0 if LAPIC is not mapped (e.g., uniprocessor).
int
lapicid(void)
{
  if (!lapic)
    return 0;
  return lapic[ID] >> 24; // APIC ID is in bits 31:24 of the ID register.
}

// Acknowledge an interrupt by writing to the EOI (End Of Interrupt) register.
// This must be called by the interrupt handler after processing an interrupt
// delivered by the Local APIC. It signals to the LAPIC that it can now deliver
// the next interrupt (if any are pending and have higher or equal priority than
// the one just serviced, depending on TPR settings).
void
lapiceoi(void)
{
  if(lapic)
    lapicw(EOI, 0); // Write 0 to EOI register.
}

// Spin for a given number of microseconds.
// This is a placeholder in xv6 and doesn't provide an actual calibrated delay.
// On real hardware, this would need to be tuned or use a calibrated timer.
// For simulation environments like Bochs or QEMU, CPU speed can vary greatly,
// making simple loop-based delays unreliable.
void
microdelay(int us)
{
  // This function is intentionally left blank in xv6.
  // A real implementation would involve a calibrated loop or using a high-resolution timer.
}

#define CMOS_PORT    0x70 // CMOS address port.
#define CMOS_RETURN  0x71 // CMOS data port.

// Start an Application Processor (AP) executing code at `addr`.
// This function implements the "Universal Startup Algorithm" using IPIs,
// as described in the Multiprocessor Specification.
// It's called by the Bootstrap Processor (BSP) to wake up other CPUs.
// - `apicid`: The LAPIC ID of the AP to start.
// - `addr`: The physical address where the AP should start execution (must be < 1MB and page-aligned).
//
// Steps:
// 1. CMOS Shutdown Code: Set CMOS shutdown status byte (offset 0xF) to 0x0A.
//    This tells POST/BIOS that a warm reset is occurring.
// 2. Warm Reset Vector: Set the warm reset vector at physical address 0x40:0x67
//    (0x467) to point to the AP's startup code (`addr`). The vector stores
//    `addr >> 4` in its segment part and 0 in its offset part.
// 3. Send INIT IPI:
//    - Configure Interrupt Command Register (ICR) to send an INIT IPI (level-triggered, assert)
//      to the target `apicid`.
//    - Wait for delivery and then de-assert the INIT signal by sending another INIT IPI (level-triggered, de-assert).
//    - A delay is included as per specification.
// 4. Send STARTUP IPI (SIPI):
//    - Configure ICR to send a STARTUP IPI to the target `apicid`, with the
//      startup address `addr` (divided by 4096, as SIPI uses the upper bits of `addr`
//      to form a 20-bit address `0VV000h` where VV is the vector from ICR).
//    - This is done twice, as per Intel's algorithm, though the second one might be
//      ignored by some hardware/emulators.
//    - Delays are included.
// After receiving the SIPI, the AP should wake up, initialize itself, and start executing
// at `addr` (which points to `entryother.S` in xv6).
void
lapicstartap(uchar apicid, uint addr)
{
  int i;
  ushort *wrv;

  // "The BSP must initialize CMOS shutdown code to 0AH
  // and the warm reset vector (DWORD based at 40:67) to point at
  // the AP startup code prior to the [universal startup algorithm]."
  outb(CMOS_PORT, 0xF);  // offset 0xF is shutdown code
  outb(CMOS_PORT+1, 0x0A);
  wrv = (ushort*)P2V((0x40<<4 | 0x67));  // Warm reset vector
  wrv[0] = 0;
  wrv[1] = addr >> 4;

  // "Universal startup algorithm."
  // Send INIT (level-triggered) interrupt to reset other CPU.
  lapicw(ICRHI, apicid<<24);
  lapicw(ICRLO, INIT | LEVEL | ASSERT);
  microdelay(200);
  lapicw(ICRLO, INIT | LEVEL);
  microdelay(100);    // should be 10ms, but too slow in Bochs!

  // Send startup IPI (twice!) to enter code.
  // Regular hardware is supposed to only accept a STARTUP
  // when it is in the halted state due to an INIT.  So the second
  // should be ignored, but it is part of the official Intel algorithm.
  // Bochs complains about the second one.  Too bad for Bochs.
  for(i = 0; i < 2; i++){
    lapicw(ICRHI, apicid<<24);
    lapicw(ICRLO, STARTUP | (addr>>12));
    microdelay(200);
  }
}

#define CMOS_STATA   0x0a
#define CMOS_STATB   0x0b
#define CMOS_UIP    (1 << 7)        // RTC update in progress

#define SECS    0x00
#define MINS    0x02
#define HOURS   0x04
#define DAY     0x07
#define MONTH   0x08
#define YEAR    0x09

static uint
cmos_read(uint reg)
{
  outb(CMOS_PORT,  reg);
  microdelay(200);

  return inb(CMOS_RETURN);
}

static void
fill_rtcdate(struct rtcdate *r)
{
  r->second = cmos_read(SECS);
  r->minute = cmos_read(MINS);
  r->hour   = cmos_read(HOURS);
  r->day    = cmos_read(DAY);
  r->month  = cmos_read(MONTH);
  r->year   = cmos_read(YEAR);
}

// qemu seems to use 24-hour GWT and the values are BCD encoded
void
cmostime(struct rtcdate *r)
{
  struct rtcdate t1, t2;
  int sb, bcd;

  sb = cmos_read(CMOS_STATB);

  bcd = (sb & (1 << 2)) == 0;

  // make sure CMOS doesn't modify time while we read it
  for(;;) {
    fill_rtcdate(&t1);
    if(cmos_read(CMOS_STATA) & CMOS_UIP)
        continue;
    fill_rtcdate(&t2);
    if(memcmp(&t1, &t2, sizeof(t1)) == 0)
      break;
  }

  // convert
  if(bcd) {
#define    CONV(x)     (t1.x = ((t1.x >> 4) * 10) + (t1.x & 0xf))
    CONV(second);
    CONV(minute);
    CONV(hour  );
    CONV(day   );
    CONV(month );
    CONV(year  );
#undef     CONV
  }

  *r = t1;
  r->year += 2000;
}
